# Generated by Django 2.0.4 on 2018-07-27 06:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='HWFCourseClassInvitation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qr', models.FileField(upload_to='invitation_qr')),
                ('course', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='data.HWFCourseClass')),
            ],
        ),
    ]
