# Generated by Django 2.0.4 on 2018-07-17 09:08

import data.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='class_number',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='gender',
            field=models.TextField(choices=[('male', 'male'), ('female', 'female')], default='male'),
        ),
        migrations.AddField(
            model_name='user',
            name='name',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='user',
            name='usertype',
            field=models.TextField(choices=[('student', 'student'), ('teacher', 'teacher'), ('assistant', 'assistant')], default='student'),
        ),
        migrations.AddField(
            model_name='user',
            name='wechat',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='user',
            name='bupt_id',
            field=models.CharField(default=data.models.default_bupt_id, max_length=10, unique=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='phone',
            field=models.CharField(default=data.models.default_phone, max_length=11, unique=True),
        ),
    ]
