# Generated by Django 2.0.4 on 2018-07-27 06:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0002_hwfcourseclassinvitation'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hwfcourseclassinvitation',
            name='course',
        ),
        migrations.RemoveField(
            model_name='hwfcourseclass',
            name='join_code',
        ),
        migrations.AddField(
            model_name='hwfcourseclass',
            name='join_qr',
            field=models.FileField(null=True, upload_to='invitation_qr'),
        ),
        migrations.DeleteModel(
            name='HWFCourseClassInvitation',
        ),
    ]
