# Generated by Django 2.0.4 on 2018-07-17 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0002_auto_20180717_1708'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='class_number',
            field=models.CharField(default='noClass', max_length=10),
        ),
        migrations.AlterField(
            model_name='user',
            name='gender',
            field=models.CharField(choices=[('male', 'male'), ('female', 'female')], default='male', max_length=6),
        ),
        migrations.AlterField(
            model_name='user',
            name='usertype',
            field=models.CharField(choices=[('student', 'student'), ('teacher', 'teacher'), ('assistant', 'assistant')], default='student', max_length=20),
        ),
    ]
