# Generated by Django 2.0.4 on 2018-07-27 06:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0003_auto_20180727_1427'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hwfcourseclass',
            name='join_qr',
        ),
        migrations.AddField(
            model_name='hwfcourseclass',
            name='join_code',
            field=models.TextField(max_length=512, null=True),
        ),
    ]
