# Generated by Django 2.0.4 on 2018-07-21 04:34

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0003_auto_20180721_1233'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hwfcourseclass',
            name='students',
            field=models.ManyToManyField(default=[], null=True, related_name='students_course', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='hwfcourseclass',
            name='teaching_assistants',
            field=models.ManyToManyField(default=[], null=True, related_name='teaching_assistants_course', to=settings.AUTH_USER_MODEL),
        ),
    ]
