# Generated by Django 2.0.4 on 2018-07-21 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0004_auto_20180721_1234'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='forgotten',
            field=models.BooleanField(default=False),
        ),
    ]
