# Generated by Django 2.0.4 on 2018-07-17 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0004_auto_20180717_1737'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='data_joined',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
