# Generated by Django 2.0.4 on 2018-07-31 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0004_auto_20180727_1431'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='wechat',
            field=models.TextField(null=True),
        ),
    ]
