# Generated by Django 2.0.4 on 2018-07-17 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0005_user_data_joined'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='data_joined',
        ),
        migrations.AlterField(
            model_name='user',
            name='date_joined',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
