# Generated by Django 2.0.4 on 2018-07-31 14:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0005_auto_20180731_1738'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserAvatar',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url_height', models.PositiveIntegerField(default=75)),
                ('url_width', models.PositiveIntegerField(default=75)),
                ('useravatar', models.ImageField(height_field='url_height', null=True, upload_to='avatars', width_field='url_width')),
            ],
        ),
        migrations.RemoveField(
            model_name='user',
            name='url_height',
        ),
        migrations.RemoveField(
            model_name='user',
            name='url_width',
        ),
        migrations.RemoveField(
            model_name='user',
            name='useravatar',
        ),
        migrations.AddField(
            model_name='useravatar',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='useravatar', to=settings.AUTH_USER_MODEL),
        ),
    ]
