# Generated by Django 2.0.4 on 2018-07-22 03:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0006_useravatar'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='useravatar',
            name='user',
        ),
        migrations.AddField(
            model_name='user',
            name='avatar',
            field=models.ImageField(height_field='url_height', null=True, upload_to='avatars', width_field='url_width'),
        ),
        migrations.AddField(
            model_name='user',
            name='url_height',
            field=models.PositiveIntegerField(default=75),
        ),
        migrations.AddField(
            model_name='user',
            name='url_width',
            field=models.PositiveIntegerField(default=75),
        ),
        migrations.DeleteModel(
            name='UserAvatar',
        ),
    ]
