# Generated by Django 2.0.4 on 2018-08-04 07:55

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0007_auto_20180804_1540'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='useravatar',
            name='user',
        ),
        migrations.AddField(
            model_name='useravatar',
            name='user',
            field=models.ManyToManyField(related_name='useravatar', to=settings.AUTH_USER_MODEL),
        ),
    ]
