# Generated by Django 2.0.4 on 2018-07-22 03:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0007_auto_20180722_1109'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='avatar',
            new_name='useravatar',
        ),
    ]
