# Generated by Django 2.0.4 on 2018-08-18 03:04

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0008_auto_20180804_1555'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hwfcourseclass',
            name='creator',
        ),
        migrations.AddField(
            model_name='hwfcourseclass',
            name='teachers',
            field=models.ManyToManyField(default=[], null=True, related_name='teachers_course', to=settings.AUTH_USER_MODEL),
        ),
    ]
