# Generated by Django 2.0.4 on 2018-08-18 03:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0009_auto_20180818_1104'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hwfcourseclass',
            name='join_code',
        ),
    ]
