# Generated by Django 2.0.4 on 2018-08-18 04:42

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0012_auto_20180818_1214'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hwfcourseclass',
            name='students',
            field=models.ManyToManyField(blank=True, null=True, related_name='students_course', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='hwfcourseclass',
            name='teachers',
            field=models.ManyToManyField(blank=True, null=True, related_name='teachers_course', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='hwfcourseclass',
            name='teaching_assistants',
            field=models.ManyToManyField(blank=True, null=True, related_name='teaching_assistants_course', to=settings.AUTH_USER_MODEL),
        ),
    ]
