# Generated by Django 2.0.4 on 2018-08-22 04:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0013_auto_20180818_1242'),
    ]

    operations = [
        migrations.AddField(
            model_name='hwfcourseclass',
            name='end_time',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='hwfcourseclass',
            name='start_time',
            field=models.DateField(blank=True, null=True),
        ),
    ]
