# Generated by Django 2.0.4 on 2018-08-22 04:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0014_auto_20180822_1239'),
    ]

    operations = [
        migrations.AddField(
            model_name='hwfcourseclass',
            name='school',
            field=models.TextField(blank=True, null=True),
        ),
    ]
