# Generated by Django 2.0.4 on 2018-08-22 04:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0015_hwfcourseclass_school'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hwfcourseclass',
            name='end_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='hwfcourseclass',
            name='start_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
