# Generated by Django 2.0.4 on 2018-09-20 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0016_auto_20180822_1248'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hwfassignment',
            name='addfile',
            field=models.ManyToManyField(blank=True, null=True, related_name='assignment', to='data.HWFFile'),
        ),
    ]
