# Generated by Django 2.0.4 on 2018-09-21 14:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0017_auto_20180920_2028'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hwffile',
            name='extension',
        ),
        migrations.RemoveField(
            model_name='hwffilequestion',
            name='support_extensions',
        ),
        migrations.DeleteModel(
            name='HWFSupportFileExtension',
        ),
    ]
