# Generated by Django 2.0.4 on 2018-09-22 02:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0018_auto_20180921_2205'),
    ]

    operations = [
        migrations.AddField(
            model_name='hwfassignment',
            name='type',
            field=models.CharField(choices=[('image', 'image'), ('docs', 'docs'), ('vary', 'vary')], default='all', max_length=20),
        ),
    ]
