# Generated by Django 2.0.4 on 2018-10-08 07:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0019_hwfassignment_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('send_time', models.DateTimeField(auto_now_add=True)),
                ('read', models.BooleanField(default=False)),
                ('content', models.TextField()),
                ('receiver', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='in_message', to=settings.AUTH_USER_MODEL)),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='out_message', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='hwfsubmission',
            name='addfile',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='addfile_submission', to='data.HWFFile'),
        ),
        migrations.AddField(
            model_name='hwfsubmission',
            name='image',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='image_submission', to='data.HWFFile'),
        ),
        migrations.AlterField(
            model_name='hwfsubmission',
            name='assignment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='assignment_submission', to='data.HWFAssignment'),
        ),
        migrations.AlterField(
            model_name='hwfsubmission',
            name='submitter',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='my_submission', to=settings.AUTH_USER_MODEL),
        ),
    ]
