# Generated by Django 2.0.4 on 2018-10-08 07:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0020_auto_20181008_1554'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hwfsubmission',
            name='score',
            field=models.FloatField(default=0.0),
        ),
    ]
