# Generated by Django 2.0.4 on 2018-10-09 04:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0021_auto_20181008_1557'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hwfsubmission',
            name='description',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='hwfsubmission',
            name='submit_time',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
