# Generated by Django 2.0.4 on 2018-10-09 04:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0022_auto_20181009_1218'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hwfassignment',
            name='description',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='hwfcourseclass',
            name='description',
            field=models.TextField(default=''),
        ),
    ]
