# Generated by Django 2.0.4 on 2018-10-09 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0023_auto_20181009_1249'),
    ]

    operations = [
        migrations.AddField(
            model_name='hwfsubmission',
            name='is_excellent',
            field=models.BooleanField(default=False),
        ),
    ]
